INPUT_BOX_WIDTH = 30
LABEL_WIDTH = 8
PADX = 10
PADY = 5

UART_CV_WIDTH = int((INPUT_BOX_WIDTH + LABEL_WIDTH) * 10)
UART_CV_HEIGHT = 300

GEN_CV_WIDTH = 500
GEN_CV_HEIGHT = UART_CV_HEIGHT

ROOT_WIDTH = UART_CV_WIDTH + GEN_CV_WIDTH + 2 * PADX
ROOT_HEIGHT = UART_CV_HEIGHT + PADY

BTN_WIDTH = 10
